version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: KoparyBase