spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    #url: jdbc:h2:~/liquibase;DB_CLOSE_ON_EXIT=FALSE
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase-changelog.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect